services:
  dev:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - m2_cache:/home/vscode/.m2
    command: sleep infinity

  paper:
    build:
      context: .
      dockerfile: ./paper/Dockerfile
      target: runtime
    ports:
      - "25565:25565"
    volumes:
      - paper_data:/server
      - ./target:/server/plugins

volumes:
  paper_data:
  m2_cache:
