version: '3.8'

services:
# 開発用コンテナ
# プラグインのビルド(コンパイル)はこのコンテナ内で行います。
  development: 
    build: 
      context: .
      dockerfile: .docker/development/Dockerfile
    container_name: mc-plugin-dev
    working_dir: /app
    volumes:
    # ローカルのプロジェクトフォルダをコンテナの/appに同期します。
    # これにより、ローカルでコードを編集すると即座にコンテナ内に反映されます。
      -.:app
      - gradle_cache:/root/.gradle
    # コンテナを起動し続け、`docker-compose exec`で中に入れるようにします。
    tty: true
    stdin_open: true

  # paperサーバーコンテナ
  # 開発したプラグインをテストするマイクラサーバー
  paper:
    build: 
      context: .
      dockerfile: ./docker/paper/Dockerfile
    container_name: mc-plugin-paper
    ports:
      -"25565:25565"    # マイクラサーバーのポート
    volumes:
      # developmentコンテナでビルドしたjarファイルを、サーバーのpluginsフォルダに配置
      -./build/libs:/server/plugins
      - paper_data:/server
    # サーバーの起動にはEURAへの同意が必須
    environment:
      - EULA="TRUE"
    # developmentコンテナが起動してからpaperが起動するよう設定
    depends_on:
      - development

# dockerが管理するデータ領域(ボリューム)の定義
volumes:
  grable_cache:
  paper_data:
