services:
  paper:
    build:
      context: .
      dockerfile: ./paper/Dockerfile
    container_name: mc-plugin-paper
    ports:
      - "25565:25565"
    volumes:
      - ./target:/server/plugins
      - paper_data:/server

volumes:
  paper_data:
