services:
  dev:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - m2_cache:/home/vscode/.m2
    command: sleep infinity

  paper:
    build:
      context: .
      dockerfile: ./paper/Dockerfile
    container_name: mc-plugin-paper
    ports:
      - "25565:25565"
    volumes:
      - ./target:/server/plugins
      - paper_data:/server
    depends_on:
      - dev

volumes:
  paper_data:
  m2_cache:
